services:
  frontend:
    image: nginx:alpine
    volumes:
      - ./dist:/usr/share/nginx/html:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app1-frontend.rule=Host(`website.santoriello.com`)"
      - "traefik.http.routers.app1-frontend.entrypoints=websecure"
      - "traefik.http.routers.app1-frontend.tls.certresolver=le"
      - "traefik.http.services.app1-frontend.loadbalancer.server.port=80"
      - "traefik.http.routers.app1-frontend.middlewares=gzip-compress,security-headers"
    networks:
      - proxy-network
